export const ChatEventEnum = Object.freeze({
  CONNECTED_EVENT: "connected",
  DISCONNECT_EVENT: "disconnect",
  JOIN_CHAT_EVENT: "joinChat",
  LEAVE_CHAT_EVENT: "leaveChat",
  UPDATE_GROUP_NAME_EVENT: "updateGroupName",
  MESSAGE_RECEIVED_EVENT: "messageReceived",
  MESSAGE_EDIT_EVENT: "messageEdited",
  MESSAGE_DELETE_EVENT: "messageDeleted",
  SOCKET_ERROR_EVENT: "socketError",
  MESSAGE_READ_EVENT: "messages_read",
  NEW_REQUEST: "friend_request_sent",
  STATUS_UPDATE: "friend_request_status_update",
  UNREAD_COUNT_UPDATE:"UNREAD_COUNT_UPDATE",
});
